# Generated by Django 3.0.3 on 2020-02-29 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='date started')),
                ('due_date', models.DateTimeField(verbose_name='due date')),
                ('status', models.CharField(choices=[('td', 'To Do'), ('dg', 'Doing'), ('rv', 'Needs Review'), ('dn', 'Done')], default='td', max_length=2)),
                ('project',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='api.Project')),
            ],
        ),
    ]
